services:
  - type: worker
    name: ocrtts-bot
    runtime: python
    region: frankfurt  # или выберите ближайший к вам: frankfurt, oregon, singapore
    plan: free
    branch: main
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg tesseract-ocr tesseract-ocr-rus
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8627063543:AAHvc33DfNFjcVT--sKfgHsCVyemY72fQ7Q
